### ISSUE TITLE
Document dataset creation process

### ISSUE THREAD

**Issue by jnehring** [freme-project/dataset-conversion-scripts#1]
For each dataset in FREME add the conversion scripts to this repository. Information on the script should be provided on datahub.io

**Comment by m1ci** [comment]
done for the grid and orcid.

**Comment by m1ci** [comment]
@jnehring do we miss any other scripts?

**Comment by jnehring** [comment]
- We miss global airports: #5 
- Further the cordis script needs a readme file.

So now we have at least all scripts that convert datasets for upload in FREME NER. Do the same scripts generate data for the entitlabels in the triple store? I guess for this feature we need an additional script, to pick to most important label when there are multiple labels for an entity.

**Comment by m1ci** [comment]
> Further the cordis script needs a readme file.

Done. See https://github.com/freme-project/dataset-conversion-scripts/tree/master/cordis-scripts

> Do the same scripts generate data for the entity labels in the triple store?

Yes. Basically, the same datasets can be submitted to FREME NER and the dc:label, foaf:name, skos:prefLabel, skos:altLabel being indexed. What properties should/could be indexed is dataset specific. For some skos, for some foaf.

**Comment by jnehring** [comment]
I think this issue is finished, thank you @m1ci
