### ISSUE TITLE
unable to push?

### ISSUE THREAD

**Issue by m1ci** [freme-project/dataset-conversion-scripts#2]
@jnehring can you please check if anyone can push to the repo? Asking cause I have problem to push some scripts.

> remote: Permission to freme-project/dataset-conversion-scripts.git denied to m1ci.
> fatal: unable to access 'https://github.com/freme-project/dataset-conversion-scripts/': The requested URL returned error: 403

**Comment by jnehring** [comment]
please try again. i changed infais permissions to "write"

**Comment by m1ci** [comment]
works now, thanks!
