### ISSUE TITLE
Add global airports conversion script

### ISSUE THREAD

**Issue by jnehring** [freme-project/dataset-conversion-scripts#5]
@fsasaki  If I remember right, you converted the global airports dataset. Can you please add the script together with a short readme to this repository?

**Comment by fsasaki** [comment]
Thanks, Jan, will do.

**Comment by fsasaki** [comment]
I know it is embarrassing but I don't have the conversion script anymore. I
did the conversion using open refine. I could re-do it but it would take
some time. Can we check with the partners if there is really a need for
this data set or if it can be dropped?

2016-08-23 12:37 GMT+02:00 Jan Nehring notifications@github.com:

**Comment by jnehring** [comment]
> Can we check with the partners if there is really a need for
> this data set or if it can be dropped?

ok no problem. will ask @freme-project/vistatec

**Comment by jnehring** [comment]
they send me a message they do not need the script for now. so i can close this issue
